### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by liampauling** [cmanaha/python-elasticsearch-logger#7]
Hi,

Want to start using this in production as it looks to be a lot easier than using logstash however I found issues with the following:

- socket.gethostbyname(socket.gethostname()) causes an error when used locally on my MBP

- If the index doesn't already exist there is no error, add function to check index exists at the start?

- A new client is created on each flush, is this needed?

**Comment by cmanaha** [comment]
Thanks for your contribution Liam.

* Will double check the failure on os.X. Could you send more details of the error? 

* Not entirely sure that is a good option (at least not by default). Here is the rationale (happy to discuss this though). When logs are inserted the index name is used as a prefix and the date gets appended to the index name. The bulk operation creates the index automatically if it does not exist. Storing the data in per-day indices makes sense as it helps with retention policies and dropping entire indices when running system maintenance (cleaning up space, etc..). 

Checking if the index exist prior to startup needs to overcome 2 challenges (rationale required); (a) What is the action if the index is not there (create? it was already going to be done anyway, Fail, I'm not convinced about log handlers getting in the way of code execution). (b) do we want to support code that leads to wrong practices (big indices with log retention managed by ttl instead of per day/per month indices... note aliases can be used to aggregate access to all indices in queries). 

Codewise the options can be added using the current schema by default and adding 2 extra variables and changing the name-index to support date regular expressions (which might be a good idea to support monthly indices for example on applications that barely log a few hundred lines a day)

Hope this makes sense. 

* As for the client being generated each time. This is a very fair point. A bit more obscure than one thinks, but make sense to refactor. Feel free to contribute, otherwise I'll try to add it as soon as I get some spare time.  The edge case is with the Kerberos client. Kerberos tokens do expire, the session held needs to be re-established after a while. That said, there is no reason to do the right thing (re-use the client, and if possible the HTTP connection) for the rest of authentication methods.

**Comment by liampauling** [comment]
Ah didn't realise bulk creates the index so ignore that comment, although monthly logs is an idea.

gethostname() returns 'Liams-MacBook-Pro.local', this then throws an error when used by gethostbyname()

I assume the logical thing to do is to ping the server before every flush or every n flushes depending on how long a ping takes compared to recreating a client and then only recreate the client if there is an error.

Another thing I noticed, is a thread lock on flush required? As technically it could result in duplicate logs being sent.

Not sure why this isn't more popular, its a dream compared to using logstash!
